### PR TITLE
Pay 6761

### PR DESCRIPTION
**Pull request by Thor-tech-of-metal**
PAY-6761: Continue on retro remission screen enabled/disabled
           [PAY-6761] (https://tools.hmcts.net/jira/browse/PAY-6761).

### CODE REVIEW

**Comment by Thor-tech-of-metal** [comment]
This PR has to be merged after https://tools.hmcts.net/jira/browse/PAY-5985 is  merged !

**Review by Ollie-Smith — DISMISSED** [review]
reviewed

**Comment by davejones74** [comment]
Beta package not to be included in this change, hence 'Do not merge' label.

**Review by Ollie-Smith — APPROVED** [review]
reviewed

**Pull request merged**
