### PR TITLE
PAY-5980: Duplicate PBA Payments - API Hash Code Changes

### PR DESCRIPTION
**Pull request by Thor-tech-of-metal**
PAY-5980: Duplicate PBA Payments - API Hash Code Changes
           [PAY-5980] (https://tools.hmcts.net/jira/browse/PAY-5980).

### CODE REVIEW

**Review by Ollie-Smith — DISMISSED** [review]
reviewed

**Review by Ollie-Smith — DISMISSED** [review]
Reviewed

**Review by Ollie-Smith — APPROVED** [review]
approved and reviewed

**Review by Ollie-Smith — APPROVED** [review]
Reviewed

**Review by davejones74 — APPROVED** [review]

**Pull request merged**
